#Numpy Library

### Section 11: Create a sample dataset with various types of data (numerical, categorical, and datetime)

**(mean,std,number of samples)**

**In the code col1 = np.random.normal(250, 10, 500), the parameters 250, 10, and 500 represent the following:**

* 250: This is the **mean (average)** of the normal distribution. It determines the center of the distribution.

* 10: This is the **standard deviation** of the normal distribution. It measures the spread or dispersion of the data around the mean. A smaller standard deviation means the data points are closer to the mean, while a larger standard deviation means they are more spread out.

* 500: This is the **number of samples** to be generated from the normal distribution. It specifies how many data points will be created.

In summary, np.random.normal(250, 10, 500) generates 500 random samples from a normal distribution with a mean of 250 and a standard deviation of 10.

<img src="https://media.licdn.com/dms/image/C4E12AQEzqOa09HO4Sw/article-cover_image-shrink_720_1280/0/1594321907240?e=2147483647&v=beta&t=-K7sr32VgioyqJ3TErswl4STqZgZZ_GFKhwervWKYHo"/>

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

#create numerical data (or numerical column)
#all those column that will be int or float

col1 = np.random.normal(250, 10, 500) #(mean,std,number of samples)
col2 = np.random.normal(100, 20, 500)
col3 = np.random.normal(750, 5, 500)

#create categorical data

categorical_data = ['A','B','C','D','F','G','H','I','J']

col4 = np.random.choice(categorical_data, 500)
col5 = np.random.choice(categorical_data, 500)

#create data time

start_date = datetime(2022, 1, 1)
end_date = datetime(2024, 1, 1)

delta = end_date - start_date

date_list = [start_date + timedelta(days=x) for x in range(delta.days)]

col6 = np.random.choice(date_list, 500)

#combine all the columns

data = np.column_stack((col1,col2,col3,col4,col5,col6))

df = pd.DataFrame(data)
df.head()

            0           1           2  3  4          5
0  245.475795  102.102894    754.1416  H  B 2023-07-14
1  258.593458  129.742059  755.734629  C  H 2022-08-23
2  259.956922   89.938845   747.98945  J  D 2023-10-31
3  243.080464  110.307832  751.859242  G  C 2023-04-14
4  247.711628  118.053723   749.47901  I  C 2022-04-17

### Section 11.1: Rename The Column Index

* Notice how the columns above named " 0, 1, 2, 3, 4, 5"
* We will now rename those columns

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

#create numerical data (or numerical column)
#all those column that will be int or float

col1 = np.random.normal(250, 10, 500)
col2 = np.random.normal(100, 20, 500)
col3 = np.random.normal(750, 5, 500)

#create categorical data

categorical_data = ['A','B','C','D','F','G','H','I','J']

col4 = np.random.choice(categorical_data, 500)
col5 = np.random.choice(categorical_data, 500)

#create data time

start_data = datetime(2022, 1, 1) # This variable was originally named 'start_data'
end_date = datetime(2024, 1, 1)

# Use 'start_data' instead of 'start_date'
delta = end_date - start_data

date_list = [start_data + timedelta(days=x) for x in range(delta.days)]

col6 = np.random.choice(date_list, 500)

#combine all the columns

data = np.column_stack((col1,col2,col3,col4,col5,col6))

df = pd.DataFrame(data, columns =['Num1','Num2','Num3','Cat1','Cat2','Date'])
df.head() # Call the head() method to display the DataFrame

         Num1        Num2        Num3 Cat1 Cat2       Date
0  248.630871    68.94102  747.502044    G    G 2023-11-10
1  257.875887   96.538454  753.079791    A    A 2022-06-04
2  267.946691  135.623917  751.203905    I    B 2022-01-19
3  236.936966  101.001934  748.138039    B    C 2022-05-09
4  258.086427   73.325494  756.337424    B    H 2022-06-20

In [ ]:
df.shape

(500, 6)

### Section 11.2: Wrong Data Type

you will notice that 'num1' num2' 'num3' is considered "object" not float (so it's normal that data labelled wrong data type, so we have to fix it)

In [ ]:
df.info()
# you will notice that 'num1-3' is considered object not float (so it's normal that data labelled wrong data type, so we have to fix it)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Num1    500 non-null    object
 1   Num2    500 non-null    object
 2   Num3    500 non-null    object
 3   Cat1    500 non-null    object
 4   Cat2    500 non-null    object
 5   Date    500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 23.6+ KB

ERROR ALERT!!

when we describe:
* we will not get any result but date
this is because all the data type is object

In [ ]:
df.describe()
#This will only describe numerical datatype

             Num1        Num2        Num3                           Date
count  500.000000  500.000000  500.000000                            500
mean   249.955203  100.600495  749.815830  2023-01-11 05:19:40.799999744
min    221.754649   46.552632  736.140471            2022-01-02 00:00:00
25%    243.100650   86.683467  746.677061            2022-07-13 18:00:00
50%    249.913608   99.780766  749.530250            2023-01-14 00:00:00
75%    256.805555  114.122522  753.245940            2023-07-20 06:00:00
max    281.311552  156.356684  763.181133            2023-12-31 00:00:00
std     10.248691   19.781309    5.108138                            NaN

In [ ]:
df.describe(include='all')
# (include='all) will describe all categorical and numerical datatype
# NaN = Not A Number

,Num1,Num2,Num3,Cat1,Cat2,Date
count,500.000000,500.000000,500.000000,500,500,500
unique,500.000000,500.000000,500.000000,9,9,NaN
top,259.061853,91.928727,747.355464,I,F,NaN
freq,1.000000,1.000000,1.000000,69,64,NaN
mean,NaN,NaN,NaN,NaN,NaN,2023-01-11 05:19:40.799999744
min,NaN,NaN,NaN,NaN,NaN,2022-01-02 00:00:00
25%,NaN,NaN,NaN,NaN,NaN,2022-07-13 18:00:00
50%,NaN,NaN,NaN,NaN,NaN,2023-01-14 00:00:00
75%,NaN,NaN,NaN,NaN,NaN,2023-07-20 06:00:00
max,NaN,NaN,NaN,NaN,NaN,2023-12-31 00:00:00

### Section 11.3: Labelling The Right Data Type

Converting object datatype to float/interger

In [ ]:
#Changing one:
df['Num1'] = df['Num1'].astype(float)

#Changing multiple at once:
df[['Num2','Num3']] = df[['Num2','Num3']].astype(float)

df.dtypes #ways to check the datatype

Num1           float64
Num2           float64
Num3           float64
Cat1            object
Cat2            object
Date    datetime64[ns]
dtype: object

In [ ]:
df.describe()
#notice how it will only described numerical datatypes

             Num1        Num2        Num3                           Date
count  500.000000  500.000000  500.000000                            500
mean   249.955203  100.600495  749.815830  2023-01-11 05:19:40.799999744
min    221.754649   46.552632  736.140471            2022-01-02 00:00:00
25%    243.100650   86.683467  746.677061            2022-07-13 18:00:00
50%    249.913608   99.780766  749.530250            2023-01-14 00:00:00
75%    256.805555  114.122522  753.245940            2023-07-20 06:00:00
max    281.311552  156.356684  763.181133            2023-12-31 00:00:00
std     10.248691   19.781309    5.108138                            NaN

In [ ]:
df.describe(include='all')
#Now notice how it will also described both numerical and categorical datatypes

,Num1,Num2,Num3,Cat1,Cat2,Date
count,500.000000,500.000000,500.000000,500,500,500
unique,NaN,NaN,NaN,9,9,NaN
top,NaN,NaN,NaN,I,F,NaN
freq,NaN,NaN,NaN,69,64,NaN
mean,249.955203,100.600495,749.815830,NaN,NaN,2023-01-11 05:19:40.799999744
min,221.754649,46.552632,736.140471,NaN,NaN,2022-01-02 00:00:00
25%,243.100650,86.683467,746.677061,NaN,NaN,2022-07-13 18:00:00
50%,249.913608,99.780766,749.530250,NaN,NaN,2023-01-14 00:00:00
75%,256.805555,114.122522,753.245940,NaN,NaN,2023-07-20 06:00:00
max,281.311552,156.356684,763.181133,NaN,NaN,2023-12-31 00:00:00
std,10.248691,19.781309,5.108138,NaN,NaN,NaN

In [ ]:
df.head(20)

          Num1        Num2        Num3 Cat1 Cat2       Date
0   259.061853   91.928727  747.355464    D    B 2022-05-16
1   248.479742   63.655152  745.426013    H    H 2023-09-29
2   263.119810   97.245207  752.305947    D    H 2022-10-24
3   242.112346  100.370024  752.522765    C    G 2022-07-04
4   240.137370  116.075914  753.431206    J    J 2023-03-09
5   239.995255   99.758384  747.674617    G    C 2023-12-23
6   237.307694  105.896619  737.605140    G    F 2023-03-04
7   261.783104   94.824570  751.016070    C    F 2022-02-10
8   239.716535   93.503268  751.088122    I    I 2022-01-11
9   255.305421   77.950790  756.914520    F    A 2023-10-16
10  269.397720   82.875696  749.127732    J    I 2022-07-07
11  259.283331   72.604518  741.895161    B    J 2023-12-07
12  245.114136  121.573199  744.204610    F    G 2023-06-29
13  244.302613  103.192728  745.290722    F    B 2023-03-31
14  243.640390   60.943026  739.509066    C    H 2023-08-11
15  237.808626  104.625761  746.620671    B    H 2023-03-20
16  251.171980  125.466611  749.847770    B    B 2023-10-16
17  243.883187   99.659152  742.852252    H    I 2023-09-23
18  252.444917   94.949980  751.986472    J    D 2023-03-05
19  266.849819   79.600590  756.350074    B    J 2022-07-13

###Exercise; Create Your Own Dataset Using Numpy

**Test 1**

In [ ]:
#TEST 1

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

#create numerical data (or numerical column)
#all those column that will be int or float

col7 = np.random.normal(500, 20, 500)
col8 = np.random.normal(100, 10, 500)
col9 = np.random.normal(950, 7, 500)

#create categorical data

categorical_data = ['Amy','Sya','Naquibah','Zura','Abidah','Saras','Nabila','Aisyah','Maryam','Anis','Hikmah']

col10 = np.random.choice(categorical_data, 500)
col11 = np.random.choice(categorical_data, 500)

#create data time

start_data = datetime(2023, 1, 1) # This variable was originally named 'start_data'
end_date = datetime(2024, 1, 1)

# Use 'start_data' instead of 'start_date'
delta = end_date - start_data

date_list = [start_data + timedelta(days=x) for x in range(delta.days)]

col12 = np.random.choice(date_list, 500)

#combine all the columns

data = np.column_stack((col7,col8,col9,col10,col11,col12))

df_T1 = pd.DataFrame(data, columns =['Num1','Num2','Num3','Name','Name2','Date'])
df_T1.head(20) # Call the head() method to display the DataFrame

          Num1        Num2        Num3      Name     Name2       Date
0   490.955764   92.838751  952.516837    Abidah  Naquibah 2023-11-09
1   515.133638  108.703849  958.166339       Amy     Saras 2023-07-21
2   507.269752  113.585858  933.691315    Abidah       Amy 2023-09-09
3   476.312855   94.618743   951.84549      Zura       Amy 2023-07-26
4   495.040673   97.364635   932.53687    Aisyah    Hikmah 2023-10-29
5   476.331197  104.271084  955.081053     Saras    Hikmah 2023-04-12
6   506.657858   81.249422  952.859039    Abidah       Amy 2023-09-05
7   499.151522   93.690642  963.172985  Naquibah       Sya 2023-10-19
8    504.34069   92.318406  951.841717    Abidah    Abidah 2023-03-06
9    512.46216   92.775614   944.02489       Amy    Aisyah 2023-07-12
10  494.363498   88.647454  955.914822    Aisyah    Nabila 2023-03-22
11  499.403878   90.819565   937.56371       Amy      Zura 2023-11-20
12   464.95911   91.383316  950.110292    Hikmah    Maryam 2023-07-19
13  488.278644   99.754688  954.805609      Zura    Maryam 2023-10-15
14  512.691554   103.78088  959.571814       Sya     Saras 2023-08-01
15  506.930556  103.761287  953.408074    Abidah    Hikmah 2023-10-06
16  505.481298  119.238346  948.190409    Nabila       Sya 2023-03-06
17  505.886001  112.638888  945.007644     Saras     Saras 2023-04-14
18  501.146006  117.440363   944.12513       Amy     Saras 2023-05-02
19  504.939787  101.525855  941.249097      Anis  Naquibah 2023-12-06

In [ ]:
df_T1.describe()

                                Date
count                            500
mean   2023-06-18 12:20:09.600000256
min              2023-01-01 00:00:00
25%              2023-03-18 18:00:00
50%              2023-06-10 12:00:00
75%              2023-09-16 00:00:00
max              2023-12-31 00:00:00

In [ ]:
df_T1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Num1    500 non-null    object
 1   Num2    500 non-null    object
 2   Num3    500 non-null    object
 3   Name    500 non-null    object
 4   Name2   500 non-null    object
 5   Date    500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 23.6+ KB

In [ ]:
df_T1.describe(include='all')

,Num1,Num2,Num3,Name,Name2,Date
count,500.000000,500.000000,500.000000,500,500,500
unique,500.000000,500.000000,500.000000,11,11,NaN
top,490.082624,106.564467,954.214176,Naquibah,Maryam,NaN
freq,1.000000,1.000000,1.000000,52,57,NaN
mean,NaN,NaN,NaN,NaN,NaN,2023-06-18 12:20:09.600000256
min,NaN,NaN,NaN,NaN,NaN,2023-01-01 00:00:00
25%,NaN,NaN,NaN,NaN,NaN,2023-03-18 18:00:00
50%,NaN,NaN,NaN,NaN,NaN,2023-06-10 12:00:00
75%,NaN,NaN,NaN,NaN,NaN,2023-09-16 00:00:00
max,NaN,NaN,NaN,NaN,NaN,2023-12-31 00:00:00

In [ ]:
#Changing multiple at once:
df_T1[['Num1','Num2','Num3']] = df_T1[['Num1','Num2','Num3']].astype(float)

df_T1.dtypes #ways to check the datatype

Num1            float64
Num2            float64
Num3            float64
Name             object
Name2            object
Date     datetime64[ns]
dtype: object

In [ ]:
df_T1.describe()

             Num1        Num2        Num3                           Date
count  500.000000  500.000000  500.000000                            500
mean   501.114927  100.285544  949.681828  2023-06-30 19:32:09.599999744
min    447.164778   69.796815  929.085740            2023-01-01 00:00:00
25%    489.182607   93.371194  945.112894            2023-03-27 00:00:00
50%    500.858775  100.124014  949.961739            2023-07-01 12:00:00
75%    513.744827  106.406437  954.021933            2023-10-05 00:00:00
max    559.149473  132.060599  971.995547            2023-12-31 00:00:00
std     19.014335    9.861645    6.950954                            NaN

In [ ]:
df_T1.describe(include='all')

,Num1,Num2,Num3,Name,Name2,Date
count,500.000000,500.000000,500.000000,500,500,500
unique,NaN,NaN,NaN,11,11,NaN
top,NaN,NaN,NaN,Zura,Amy,NaN
freq,NaN,NaN,NaN,56,52,NaN
mean,501.114927,100.285544,949.681828,NaN,NaN,2023-06-30 19:32:09.599999744
min,447.164778,69.796815,929.085740,NaN,NaN,2023-01-01 00:00:00
25%,489.182607,93.371194,945.112894,NaN,NaN,2023-03-27 00:00:00
50%,500.858775,100.124014,949.961739,NaN,NaN,2023-07-01 12:00:00
75%,513.744827,106.406437,954.021933,NaN,NaN,2023-10-05 00:00:00
max,559.149473,132.060599,971.995547,NaN,NaN,2023-12-31 00:00:00
std,19.014335,9.861645,6.950954,NaN,NaN,NaN

**Test 2**

In [ ]:
#TEST 2

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

#create numerical data (or numerical column)
#all those column that will be int or float

col7 = np.random.normal(80, 10, 11)
col8 = np.random.normal(75, 15, 11)
col9 = np.random.normal(60, 10, 11)

#create categorical data

categorical_data = ['Amy','Sya','Naquibah','Zura','Abidah','Saras','Nabila','Aisyah','Maryam','Anis','Hikmah']

col10 = np.random.choice(categorical_data, 11)

#create data time

start_data = datetime(2023, 1, 1) # This variable was originally named 'start_data'
end_date = datetime(2024, 1, 1)

# Use 'start_data' instead of 'start_date'
delta = end_date - start_data

date_list = [start_data + timedelta(days=x) for x in range(delta.days)]

col12 = np.random.choice(date_list, 11)

#combine all the columns

data = np.column_stack((col7,col8,col9,col10,col12))

df_T2 = pd.DataFrame(data, columns =['BM','BI','Sejarah','Name','Date'])
df_T2.head(12) # Call the head() method to display the DataFrame

            BM          BI    Sejarah      Name       Date
0    84.743591   87.459262  50.798962    Hikmah 2023-12-20
1    82.890306   75.933018  62.811093    Abidah 2023-09-11
2   113.045126   69.827303  47.033066       Amy 2023-07-24
3     92.62817   93.396623   64.04855  Naquibah 2023-03-21
4    72.119122   92.193672  56.595346    Abidah 2023-01-15
5    79.056969  110.475868  46.885928    Maryam 2023-05-04
6    82.720213   73.524806  76.482641    Maryam 2023-11-04
7    79.104047   94.070868  49.537952    Nabila 2023-06-14
8    68.352804   81.956693  41.519338    Maryam 2023-08-30
9    77.005051   86.327711  64.873925    Aisyah 2023-11-30
10   89.595484   85.928003  59.351316    Hikmah 2023-11-02

In [ ]:
df_T2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   BM       11 non-null     object
 1   BI       11 non-null     object
 2   Sejarah  11 non-null     object
 3   Name     11 non-null     object
 4   Date     11 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(4)
memory usage: 568.0+ bytes

In [ ]:
#Changing multiple object to float:
df_T2[['BM','BI','Sejarah']] = df_T2[['BM','BI','Sejarah']].astype(float)

df_T2.dtypes #ways to check the datatype

BM                float64
BI                float64
Sejarah           float64
Name               object
Date       datetime64[ns]
dtype: object

In [ ]:
df_T2.describe(include='all')

                BM          BI    Sejarah    Name                 Date
count    11.000000   11.000000  11.000000      11                   11
unique         NaN         NaN        NaN       7                  NaN
top            NaN         NaN        NaN  Maryam                  NaN
freq           NaN         NaN        NaN       3                  NaN
mean     83.750989   86.463075  56.358011     NaN  2023-08-05 00:00:00
min      68.352804   69.827303  41.519338     NaN  2023-01-15 00:00:00
25%      78.031010   78.944855  48.285509     NaN  2023-05-24 12:00:00
50%      82.720213   86.327711  56.595346     NaN  2023-08-30 00:00:00
75%      87.169538   92.795148  63.429822     NaN  2023-11-03 00:00:00
max     113.045126  110.475868  76.482641     NaN  2023-12-20 00:00:00
std      11.980974   11.366798  10.303406     NaN                  NaN